import { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "science-ethics",
    title: "과학의 진보와 윤리",
    description: "과학기술 발전이 사회와 개인에 미치는 윤리적 영향을 탐구합니다.",
    topic: "유전자 편집, AI 기술, 동물 실험 등 과학 발전의 윤리적 경계",
    chatHistory: [
      { id: "se-01", speaker: "A", text: "유전자 편집 기술로 유전병을 없앨 수 있다면 반드시 사용해야 한다고 생각해." },
      { id: "se-02", speaker: "B", text: "나도 유전병 치료에는 동의하지만, '편집'의 범위를 어디까지 허용할지가 문제야.", parentId: "se-01" },
      { id: "se-03", speaker: "A", text: "그 경계는 사회적 합의로 정하면 되지 않을까?", parentId: "se-02" },
      { id: "se-04", speaker: "B", text: "사회적 합의라는 게 생각보다 어려워. 나라마다 윤리 기준이 다르니까.", parentId: "se-03" },
      { id: "se-05", speaker: "A", text: "AI 의사 결정 시스템은 이미 병원에서 쓰이고 있잖아. 과학 발전은 막을 수 없어." },
      { id: "se-06", speaker: "B", text: "막는 게 아니라 속도를 조절하는 거지. 윤리 검토 없이 속도만 추구하면 위험해.", parentId: "se-05" },
      { id: "se-07", speaker: "A", text: "동물 실험 없이는 신약 개발 자체가 불가능한데 그건 어떻게 생각해?", parentId: "se-06" },
      { id: "se-08", speaker: "B", text: "대안 실험법이 개발되고 있으니까 장기적으로는 동물 실험을 줄여야 한다고 봐.", parentId: "se-07" },
      { id: "se-09", speaker: "A", text: "그러면 우리가 말한 것처럼 과학 발전을 지지하되, 각 기술마다 별도의 윤리 기준이 필요하다는 거네.", parentId: "se-08" },
      { id: "se-10", speaker: "B", text: "맞아. 기술을 하나로 묶어서 판단하는 건 단순화야.", parentId: "se-09" },
      { id: "se-11", speaker: "A", text: "사실 가장 큰 문제는 누가 그 기준을 정하느냐인 것 같아." },
      { id: "se-12", speaker: "B", text: "전문가 집단, 시민, 정부가 함께 논의하는 구조가 필요하다고 생각해.", parentId: "se-11" },
      { id: "se-13", speaker: "A", text: "그런데 기업이 그 과정에서 너무 큰 영향력을 가지면 어떡하지?", parentId: "se-12" },
      { id: "se-14", speaker: "B", text: "독립적인 윤리위원회가 필요한 이유가 바로 그거야.", parentId: "se-13" },
      { id: "se-15", speaker: "A", text: "결국 과학 발전 자체보다 거버넌스 문제가 핵심이라는 생각이 드네.", parentId: "se-14" },
      { id: "se-16", speaker: "B", text: "동의해. 기술 자체는 중립적이지만 사용 방식은 중립적이지 않으니까.", parentId: "se-15" },
      { id: "se-17", speaker: "A", text: "그 말이 이번 토론 전체를 요약하는 것 같아." },
      { id: "se-18", speaker: "B", text: "응, 처음에 내가 너무 단순하게 생각했던 것 같아. 발전 자체를 막아야 한다는 게 아니었어.", parentId: "se-17" },
      { id: "se-19", speaker: "A", text: "나도 처음엔 '기술 = 진보'로만 봤는데 윤리 구조가 없으면 진보도 퇴보가 될 수 있다는 걸 알았어.", parentId: "se-18" },
      { id: "se-20", speaker: "B", text: "좋은 대화였어. 이 내용을 발표 자료에 넣을 수 있겠다." },
    ],
  },
  {
    id: "multicultural",
    title: "다문화사회에서의 배려",
    description: "다양한 문화적 배경을 가진 구성원이 함께 살아가는 방식을 탐구합니다.",
    topic: "문화적 차이, 상호 존중, 편견 극복",
    chatHistory: [
      { id: "mc-01", speaker: "A", text: "다문화 사회에서 가장 중요한 건 서로의 문화를 인정하는 것 같아." },
      { id: "mc-02", speaker: "B", text: "인정도 중요하지만 실생활에서 어떻게 배려할지가 더 구체적인 문제야.", parentId: "mc-01" },
      { id: "mc-03", speaker: "A", text: "예를 들면 학교 급식에서 할랄 음식 옵션을 제공하는 것처럼?", parentId: "mc-02" },
      { id: "mc-04", speaker: "B", text: "맞아. 그런 제도적 배려가 없으면 '인정한다'는 말이 형식적이 돼.", parentId: "mc-03" },
      { id: "mc-05", speaker: "A", text: "근데 배려가 지나치면 역차별 논란이 생기기도 하더라고." },
      { id: "mc-06", speaker: "B", text: "역차별이라는 말 자체가 특권을 당연하게 여겼던 관점에서 나온 거 아닐까?", parentId: "mc-05" },
      { id: "mc-07", speaker: "A", text: "그 말은 좀 극단적인 것 같아. 다수도 배려받을 권리가 있지.", parentId: "mc-06" },
      { id: "mc-08", speaker: "B", text: "물론이야. 다수를 배제하자는 게 아니라 소수가 보이지 않게 배제되는 걸 막자는 거야.", parentId: "mc-07" },
      { id: "mc-09", speaker: "A", text: "그러면 배려는 소수만을 위한 게 아니라 모두가 동등하게 참여할 수 있도록 하는 거네.", parentId: "mc-08" },
      { id: "mc-10", speaker: "B", text: "맞아. 그게 진정한 포용이라고 생각해.", parentId: "mc-09" },
      { id: "mc-11", speaker: "A", text: "그런데 언어 장벽은 어떻게 해결해? 소통이 안 되면 배려도 한계가 있잖아." },
      { id: "mc-12", speaker: "B", text: "통역 지원이나 이중언어 교육이 필요한 이유가 그거야.", parentId: "mc-11" },
      { id: "mc-13", speaker: "A", text: "학교에서 다문화 교육을 더 강화해야 한다는 거지?", parentId: "mc-12" },
      { id: "mc-14", speaker: "B", text: "그뿐만 아니라 지역사회 전체가 함께 해야 해.", parentId: "mc-13" },
      { id: "mc-15", speaker: "A", text: "편견을 없애는 가장 좋은 방법은 직접 만나는 거라고 생각해.", parentId: "mc-14" },
      { id: "mc-16", speaker: "B", text: "맞아. 교류 없이는 이해도 없어.", parentId: "mc-15" },
      { id: "mc-17", speaker: "A", text: "이 대화를 통해 배려가 단순한 친절이 아니라 구조적인 변화를 포함하는 개념이라는 걸 알았어.", parentId: "mc-16" },
      { id: "mc-18", speaker: "B", text: "나도 처음보다 훨씬 넓게 생각하게 됐어.", parentId: "mc-17" },
    ],
  },
  {
    id: "family-roles",
    title: "가정 내 역할 분담",
    description: "현대 가정에서 공정한 역할 분담의 의미를 탐구합니다.",
    topic: "가사 분담, 성평등, 세대 인식 차이",
    chatHistory: [
      { id: "fr-01", speaker: "A", text: "가사는 부부가 반반 나눠야 한다고 생각해." },
      { id: "fr-02", speaker: "B", text: "원칙적으로는 맞지만, 실제로 반반이 어려운 현실적 이유도 있어.", parentId: "fr-01" },
      { id: "fr-03", speaker: "A", text: "어떤 이유?", parentId: "fr-02" },
      { id: "fr-04", speaker: "B", text: "업무 강도나 근무 시간이 다르면 집에 와서 할 수 있는 에너지 자체가 달라지잖아.", parentId: "fr-03" },
      { id: "fr-05", speaker: "A", text: "그건 인정해. 그러면 '반반'보다는 '상황에 맞게 유연하게'가 더 적절한 표현이겠다.", parentId: "fr-04" },
      { id: "fr-06", speaker: "B", text: "맞아. 근데 문제는 그 '유연함'이 항상 한 사람에게 치우치는 경향이 있다는 거야.", parentId: "fr-05" },
      { id: "fr-07", speaker: "A", text: "주로 여성에게 치우치는 거 말하는 거지?", parentId: "fr-06" },
      { id: "fr-08", speaker: "B", text: "응. 통계적으로도 그게 입증돼 있어. 무급 돌봄 노동의 70% 이상이 여성이야.", parentId: "fr-07" },
      { id: "fr-09", speaker: "A", text: "그러면 구조적 문제인 거네. 개인 노력만으로는 해결이 안 되겠다.", parentId: "fr-08" },
      { id: "fr-10", speaker: "B", text: "육아휴직 제도나 유연근무제 같은 정책이 필요한 이유가 그거야.", parentId: "fr-09" },
      { id: "fr-11", speaker: "A", text: "어르신들은 '그게 당연한 거 아니냐'고 하시던데, 세대 차이도 있어." },
      { id: "fr-12", speaker: "B", text: "세대 인식이 다른 건 사실이야. 근데 그걸 이유로 불평등을 유지하는 건 별개 문제야.", parentId: "fr-11" },
      { id: "fr-13", speaker: "A", text: "맞아. '원래 그래왔다'는 게 '옳다'는 의미는 아니니까.", parentId: "fr-12" },
      { id: "fr-14", speaker: "B", text: "그리고 아이들도 역할 분담을 배워야 한다고 봐. 어릴 때 집안일을 돕는 경험이 중요해.", parentId: "fr-13" },
      { id: "fr-15", speaker: "A", text: "아이들 가사 참여에 대해서는 어떤 기준이 좋을까?", parentId: "fr-14" },
      { id: "fr-16", speaker: "B", text: "나이에 맞는 수준에서, 성별 구분 없이 하는 게 핵심이라고 생각해.", parentId: "fr-15" },
      { id: "fr-17", speaker: "A", text: "아들한테 설거지, 딸한테 청소 이런 식으로 나누면 안 된다는 거지.", parentId: "fr-16" },
      { id: "fr-18", speaker: "B", text: "맞아. 어릴 때부터 그런 구분을 없애야 성인이 돼서도 자연스러워지지.", parentId: "fr-17" },
      { id: "fr-19", speaker: "A", text: "결국 가정 내 역할 분담이 사회 전체의 성평등과 연결된다는 거네.", parentId: "fr-18" },
      { id: "fr-20", speaker: "B", text: "그리고 그게 행복한 가정의 기본 조건이기도 하고. 누군가 지쳐 있으면 가족 전체에 영향을 미치니까.", parentId: "fr-19" },
      { id: "fr-21", speaker: "A", text: "오늘 대화하면서 '역할 분담'이 단순한 가사 문제가 아니라는 걸 새롭게 느꼈어.", parentId: "fr-20" },
      { id: "fr-22", speaker: "B", text: "나도. 처음엔 반반이냐 아니냐의 문제인 줄 알았는데 훨씬 넓은 맥락이 있었네.", parentId: "fr-21" },
    ],
  },
  {
    id: "agentic-ai",
    title: "Agentic AI 연구 주제 논의 (선영·태상)",
    description: "박사과정 연구자 두 명이 Agentic AI의 교육적 적용 가능성과 연구 방향을 탐색합니다.",
    topic: "Agentic AI, IVR, 협동학습, 교육공학 연구 설계",
    chatHistory: [
      { id: "ag-01", speaker: "A", text: "태상아 나 요즘 Agentic AI 논문들 읽고 있는데 진짜 신기하더라. 그냥 답변만 하는 게 아니라 스스로 목표 세우고 계획짜고 실행까지 한다는 거잖아." },
      { id: "ag-02", speaker: "A", text: "근데 교육에 이걸 어떻게 쓸 수 있을지 아직 감이 잘 안 잡혀.", parentId: "ag-01" },
      { id: "ag-03", speaker: "B", text: "나도 그 부분 요즘 계속 생각하고 있었어.", parentId: "ag-02" },
      { id: "ag-04", speaker: "B", text: "IVR 환경에 넣으면 학습자랑 실시간으로 상호작용하면서 시나리오를 동적으로 바꿔줄 수 있지 않을까? 단순 NPC랑은 차원이 다른 거지.", parentId: "ag-03" },
      { id: "ag-05", speaker: "A", text: "맞아 맞아. 근데 내가 걱정하는 건 agent가 너무 주도적으로 끌고 가면 학습자의 자기조절학습이 떨어지는 거 아닐까 하는 거야.", parentId: "ag-04" },
      { id: "ag-06", speaker: "B", text: "그 포인트 완전 중요한 것 같아. 결국 얼마나 autonomy를 학습자한테 줄 거냐의 문제인 거지.", parentId: "ag-05" },
      { id: "ag-07", speaker: "A", text: "그치. 근데 나는 협동학습 맥락에서 보면 또 다른 것 같거든. 학습자 두 명이 있을 때 agent가 facilitator 역할만 하면 어떨까 싶어.", parentId: "ag-06" },
      { id: "ag-08", speaker: "A", text: "직접 답 주는 게 아니라 '지금 두 사람 의견 차이가 있는데 어떻게 생각해?' 이런 식으로.", parentId: "ag-07" },
      { id: "ag-09", speaker: "B", text: "오 그거 완전 좋은데. 근데 그게 제대로 되려면 agent가 대화 맥락을 실시간으로 파악하고 있어야 하잖아.", parentId: "ag-08" },
      { id: "ag-10", speaker: "B", text: "TKS 코드 같은 걸로 대화를 분류하면서 개입 시점을 판단하게 하면 어떨까?", parentId: "ag-09" },
      { id: "ag-11", speaker: "A", text: "!!!! 그거 진짜 좋다. 우리 지금 하는 연구랑 연결되잖아.", parentId: "ag-10" },
      { id: "ag-12", speaker: "A", text: "근데 그걸 IVR에서 구현하면 기술 난이도가 너무 높아지는 거 아닐까 걱정도 돼.", parentId: "ag-11" },
      { id: "ag-13", speaker: "B", text: "맞아. 나도 그 부분이 고민이야. 일단 텍스트 채팅 환경에서 먼저 검증하고 IVR로 확장하는 게 현실적일 것 같아.", parentId: "ag-12" },
      { id: "ag-14", speaker: "A", text: "그 방향이 논문 쓰기도 훨씬 쉽겠다. 1단계 설계 및 텍스트 환경 검증, 2단계 IVR 적용.", parentId: "ag-13" },
      { id: "ag-15", speaker: "B", text: "근데 선영아 나는 사실 Agentic AI가 교육에서 진짜 효과가 있는지 아직 회의적인 면도 있어.", parentId: "ag-14" },
      { id: "ag-16", speaker: "B", text: "지금 챗봇도 제대로 못 쓰는 학습자들이 많은데 agent는 더 복잡하잖아. 사용자 리터러시 문제가 선행되어야 하지 않나.", parentId: "ag-15" },
      { id: "ag-17", speaker: "A", text: "흠... 그건 좀 다른 관점인 것 같기도 해. 리터러시가 낮으니까 agent가 더 필요한 거 아닐까? 학습자 스스로 구조화하기 어려운 부분을 도와주는 거니까.", parentId: "ag-16" },
      { id: "ag-18", speaker: "B", text: "아 그렇게 보면 또 맞는 말이긴 해. 비계(scaffolding) 역할.", parentId: "ag-17" },
      { id: "ag-19", speaker: "A", text: "맞아. 그리고 점진적으로 지원을 줄여가는 fading 설계를 넣으면 의존성 문제도 해결될 것 같고.", parentId: "ag-18" },
      { id: "ag-20", speaker: "B", text: "그 fading 설계 논문으로 쓰기도 딱 좋겠다. 근데 어떤 기준으로 fading 시점을 결정해?", parentId: "ag-19" },
      { id: "ag-21", speaker: "A", text: "그게 지금 제일 모르겠는 부분이야... 학습자의 발화 패턴이나 코드 분포를 보고 판단하면 어떨까?", parentId: "ag-20" },
      { id: "ag-22", speaker: "A", text: "예를 들어 Integration이나 Conflict 비율이 올라가면 agent 개입 줄이는 식으로.", parentId: "ag-21" },
      { id: "ag-23", speaker: "B", text: "오 그거 진짜 좋은 아이디어다. 우리 TKS 분류기를 agent 내부 로직에 직접 넣는 거네.", parentId: "ag-22" },
      { id: "ag-24", speaker: "B", text: "근데 실시간 분류가 정확할지가 문제겠다. 지금도 LLM이 경계 사례에서 틀리는 경우 있잖아.", parentId: "ag-23" },
      { id: "ag-25", speaker: "A", text: "그건 맞아. 그래서 연구 설계할 때 분류 정확도 검증을 따로 챕터로 빼야 할 것 같아.", parentId: "ag-24" },
      { id: "ag-26", speaker: "B", text: "그러면 논문 구조가 1) 분류 시스템 설계 및 검증 2) agent 설계 3) 학습효과 검증 이렇게 3논문 모델로 가도 되겠는데?", parentId: "ag-25" },
      { id: "ag-27", speaker: "A", text: "완전 좋아. 교수님이 말씀하신 3-paper model이랑 딱 맞네.", parentId: "ag-26" },
      { id: "ag-28", speaker: "A", text: "근데 1번 논문을 먼저 써야겠다. 일단 TKS 자동 분류 정확도 검증 연구로 투고해볼게.", parentId: "ag-27" },
      { id: "ag-29", speaker: "B", text: "나도 같이 해도 돼? 나는 IVR 쪽 리뷰 논문 먼저 쓰려고 했는데 이게 더 재밌을 것 같기도 하고.", parentId: "ag-28" },
      { id: "ag-30", speaker: "A", text: "당연하지. 너 오면 분석 훨씬 빨라질 것 같아.", parentId: "ag-29" },
      { id: "ag-31", speaker: "B", text: "그리고 나는 솔직히 Agentic AI의 교육적 효과보다 학습자가 agent를 어떻게 인식하는지에 더 관심이 있어.", parentId: "ag-30" },
      { id: "ag-32", speaker: "B", text: "agent를 '도구'로 보냐 '파트너'로 보냐에 따라 상호작용 패턴이 완전 달라질 것 같거든.", parentId: "ag-31" },
      { id: "ag-33", speaker: "A", text: "맞아. 그게 사실 agency perception 연구랑 연결되는데. 흥미롭다.", parentId: "ag-32" },
      { id: "ag-34", speaker: "A", text: "근데 그건 네 독립 연구 주제로 더 어울리는 것 같기도 해. 내 CSCL이랑은 다소 달라서.", parentId: "ag-33" },
      { id: "ag-35", speaker: "B", text: "그치 ㅋㅋ 일단 우리 겹치는 부분인 TKS 분류 연구 먼저 같이 하고, 나머지는 각자 파자.", parentId: "ag-34" },
      { id: "ag-36", speaker: "A", text: "좋아. 그럼 다음주에 지윤쌤이랑 같이 킥오프 미팅 잡을게.", parentId: "ag-35" },
      { id: "ag-37", speaker: "B", text: "ㅇㅋㅇㅋ. 근데 선영아 한 가지 더. agent가 윤리적으로 개입하는 선이 어디까지냐는 문제도 연구에 넣어야 할 것 같아.", parentId: "ag-36" },
      { id: "ag-38", speaker: "A", text: "아 그거 IRB에서도 분명 물어볼 거야. agent가 학습자 발화를 실시간 수집 분석한다는 게 사생활 문제랑도 연결되니까.", parentId: "ag-37" },
      { id: "ag-39", speaker: "B", text: "그럼 연구 설계 단계에서 anonymization이나 consent 절차를 아예 섹션으로 빼야겠다. 좋아, 정리된 것 같다.", parentId: "ag-38" },
      { id: "ag-40", speaker: "A", text: "오늘 얘기하면서 생각이 많이 정리됐다. 이렇게 보니까 우리 연구 방향이 꽤 탄탄한 것 같아서 좋아.", parentId: "ag-39" },
    ],
  },
  {
    id: "low-quality",
    title: "환경 보호와 개인의 역할 (낮은 품질)",
    description: "상호참조가 적고 단절된 대화의 예시입니다. 루브릭 분석 비교용.",
    topic: "환경 보호, 개인 실천, 사회적 책임",
    chatHistory: [
      { id: "lq-01", speaker: "A", text: "환경 보호가 중요한 것 같아." },
      { id: "lq-02", speaker: "B", text: "응.", parentId: "lq-01" },
      { id: "lq-03", speaker: "A", text: "나는 분리수거 열심히 해." },
      { id: "lq-04", speaker: "B", text: "오늘 점심 뭐 먹었어?" },
      { id: "lq-05", speaker: "A", text: "김밥.", parentId: "lq-04" },
      { id: "lq-06", speaker: "B", text: "지구 온난화가 진짜 심각하대." },
      { id: "lq-07", speaker: "A", text: "맞아.", parentId: "lq-06" },
      { id: "lq-08", speaker: "B", text: "탄소 배출 줄여야 한다고 생각해." },
      { id: "lq-09", speaker: "A", text: "응 그렇지.", parentId: "lq-08" },
      { id: "lq-10", speaker: "B", text: "근데 나는 걸어 다니기 귀찮아." },
      { id: "lq-11", speaker: "A", text: "나도.", parentId: "lq-10" },
      { id: "lq-12", speaker: "B", text: "내일 체육 시간에 뭐 해?" },
      { id: "lq-13", speaker: "A", text: "축구인가?" },
      { id: "lq-14", speaker: "B", text: "재활용도 중요하지." },
      { id: "lq-15", speaker: "A", text: "맞아.", parentId: "lq-14" },
      { id: "lq-16", speaker: "B", text: "그냥 정부가 다 알아서 해야 하는 거 아닌가." },
      { id: "lq-17", speaker: "A", text: "응 맞아.", parentId: "lq-16" },
      { id: "lq-18", speaker: "B", text: "우리가 뭘 할 수 있겠어." },
      { id: "lq-19", speaker: "A", text: "그러게.", parentId: "lq-18" },
      { id: "lq-20", speaker: "B", text: "수업 끝나고 편의점 갈래?" },
    ],
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
