import { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "science-ethics",
    title: "과학의 진보와 윤리",
    description: "과학기술 발전이 사회와 개인에 미치는 윤리적 영향을 탐구합니다.",
    topic: "유전자 편집, AI 기술, 동물 실험 등 과학 발전의 윤리적 경계",
    chatHistory: [
      { id: "se-01", speaker: "A", text: "유전자 편집 기술로 유전병을 없앨 수 있다면 반드시 사용해야 한다고 생각해." },
      { id: "se-02", speaker: "B", text: "나도 유전병 치료에는 동의하지만, '편집'의 범위를 어디까지 허용할지가 문제야.", parentId: "se-01" },
      { id: "se-03", speaker: "A", text: "그 경계는 사회적 합의로 정하면 되지 않을까?", parentId: "se-02" },
      { id: "se-04", speaker: "B", text: "사회적 합의라는 게 생각보다 어려워. 나라마다 윤리 기준이 다르니까.", parentId: "se-03" },
      { id: "se-05", speaker: "A", text: "AI 의사 결정 시스템은 이미 병원에서 쓰이고 있잖아. 과학 발전은 막을 수 없어." },
      { id: "se-06", speaker: "B", text: "막는 게 아니라 속도를 조절하는 거지. 윤리 검토 없이 속도만 추구하면 위험해.", parentId: "se-05" },
      { id: "se-07", speaker: "A", text: "동물 실험 없이는 신약 개발 자체가 불가능한데 그건 어떻게 생각해?", parentId: "se-06" },
      { id: "se-08", speaker: "B", text: "대안 실험법이 개발되고 있으니까 장기적으로는 동물 실험을 줄여야 한다고 봐.", parentId: "se-07" },
      { id: "se-09", speaker: "A", text: "그러면 우리가 말한 것처럼 과학 발전을 지지하되, 각 기술마다 별도의 윤리 기준이 필요하다는 거네.", parentId: "se-08" },
      { id: "se-10", speaker: "B", text: "맞아. 기술을 하나로 묶어서 판단하는 건 단순화야.", parentId: "se-09" },
      { id: "se-11", speaker: "A", text: "사실 가장 큰 문제는 누가 그 기준을 정하느냐인 것 같아." },
      { id: "se-12", speaker: "B", text: "전문가 집단, 시민, 정부가 함께 논의하는 구조가 필요하다고 생각해.", parentId: "se-11" },
      { id: "se-13", speaker: "A", text: "그런데 기업이 그 과정에서 너무 큰 영향력을 가지면 어떡하지?", parentId: "se-12" },
      { id: "se-14", speaker: "B", text: "독립적인 윤리위원회가 필요한 이유가 바로 그거야.", parentId: "se-13" },
      { id: "se-15", speaker: "A", text: "결국 과학 발전 자체보다 거버넌스 문제가 핵심이라는 생각이 드네.", parentId: "se-14" },
      { id: "se-16", speaker: "B", text: "동의해. 기술 자체는 중립적이지만 사용 방식은 중립적이지 않으니까.", parentId: "se-15" },
      { id: "se-17", speaker: "A", text: "그 말이 이번 토론 전체를 요약하는 것 같아." },
      { id: "se-18", speaker: "B", text: "응, 처음에 내가 너무 단순하게 생각했던 것 같아. 발전 자체를 막아야 한다는 게 아니었어.", parentId: "se-17" },
      { id: "se-19", speaker: "A", text: "나도 처음엔 '기술 = 진보'로만 봤는데 윤리 구조가 없으면 진보도 퇴보가 될 수 있다는 걸 알았어.", parentId: "se-18" },
      { id: "se-20", speaker: "B", text: "좋은 대화였어. 이 내용을 발표 자료에 넣을 수 있겠다." },
    ],
  },
  {
    id: "multicultural",
    title: "다문화사회에서의 배려",
    description: "다양한 문화적 배경을 가진 구성원이 함께 살아가는 방식을 탐구합니다.",
    topic: "문화적 차이, 상호 존중, 편견 극복",
    chatHistory: [
      { id: "mc-01", speaker: "A", text: "다문화 사회에서 가장 중요한 건 서로의 문화를 인정하는 것 같아." },
      { id: "mc-02", speaker: "B", text: "인정도 중요하지만 실생활에서 어떻게 배려할지가 더 구체적인 문제야.", parentId: "mc-01" },
      { id: "mc-03", speaker: "A", text: "예를 들면 학교 급식에서 할랄 음식 옵션을 제공하는 것처럼?", parentId: "mc-02" },
      { id: "mc-04", speaker: "B", text: "맞아. 그런 제도적 배려가 없으면 '인정한다'는 말이 형식적이 돼.", parentId: "mc-03" },
      { id: "mc-05", speaker: "A", text: "근데 배려가 지나치면 역차별 논란이 생기기도 하더라고." },
      { id: "mc-06", speaker: "B", text: "역차별이라는 말 자체가 특권을 당연하게 여겼던 관점에서 나온 거 아닐까?", parentId: "mc-05" },
      { id: "mc-07", speaker: "A", text: "그 말은 좀 극단적인 것 같아. 다수도 배려받을 권리가 있지.", parentId: "mc-06" },
      { id: "mc-08", speaker: "B", text: "물론이야. 다수를 배제하자는 게 아니라 소수가 보이지 않게 배제되는 걸 막자는 거야.", parentId: "mc-07" },
      { id: "mc-09", speaker: "A", text: "그러면 배려는 소수만을 위한 게 아니라 모두가 동등하게 참여할 수 있도록 하는 거네.", parentId: "mc-08" },
      { id: "mc-10", speaker: "B", text: "맞아. 그게 진정한 포용이라고 생각해.", parentId: "mc-09" },
      { id: "mc-11", speaker: "A", text: "그런데 언어 장벽은 어떻게 해결해? 소통이 안 되면 배려도 한계가 있잖아." },
      { id: "mc-12", speaker: "B", text: "통역 지원이나 이중언어 교육이 필요한 이유가 그거야.", parentId: "mc-11" },
      { id: "mc-13", speaker: "A", text: "학교에서 다문화 교육을 더 강화해야 한다는 거지?", parentId: "mc-12" },
      { id: "mc-14", speaker: "B", text: "그뿐만 아니라 지역사회 전체가 함께 해야 해.", parentId: "mc-13" },
      { id: "mc-15", speaker: "A", text: "편견을 없애는 가장 좋은 방법은 직접 만나는 거라고 생각해.", parentId: "mc-14" },
      { id: "mc-16", speaker: "B", text: "맞아. 교류 없이는 이해도 없어.", parentId: "mc-15" },
      { id: "mc-17", speaker: "A", text: "이 대화를 통해 배려가 단순한 친절이 아니라 구조적인 변화를 포함하는 개념이라는 걸 알았어.", parentId: "mc-16" },
      { id: "mc-18", speaker: "B", text: "나도 처음보다 훨씬 넓게 생각하게 됐어.", parentId: "mc-17" },
    ],
  },
  {
    id: "family-roles",
    title: "가정 내 역할 분담",
    description: "현대 가정에서 공정한 역할 분담의 의미를 탐구합니다.",
    topic: "가사 분담, 성평등, 세대 인식 차이",
    chatHistory: [
      { id: "fr-01", speaker: "A", text: "가사는 부부가 반반 나눠야 한다고 생각해." },
      { id: "fr-02", speaker: "B", text: "원칙적으로는 맞지만, 실제로 반반이 어려운 현실적 이유도 있어.", parentId: "fr-01" },
      { id: "fr-03", speaker: "A", text: "어떤 이유?", parentId: "fr-02" },
      { id: "fr-04", speaker: "B", text: "업무 강도나 근무 시간이 다르면 집에 와서 할 수 있는 에너지 자체가 달라지잖아.", parentId: "fr-03" },
      { id: "fr-05", speaker: "A", text: "그건 인정해. 그러면 '반반'보다는 '상황에 맞게 유연하게'가 더 적절한 표현이겠다.", parentId: "fr-04" },
      { id: "fr-06", speaker: "B", text: "맞아. 근데 문제는 그 '유연함'이 항상 한 사람에게 치우치는 경향이 있다는 거야.", parentId: "fr-05" },
      { id: "fr-07", speaker: "A", text: "주로 여성에게 치우치는 거 말하는 거지?", parentId: "fr-06" },
      { id: "fr-08", speaker: "B", text: "응. 통계적으로도 그게 입증돼 있어. 무급 돌봄 노동의 70% 이상이 여성이야.", parentId: "fr-07" },
      { id: "fr-09", speaker: "A", text: "그러면 구조적 문제인 거네. 개인 노력만으로는 해결이 안 되겠다.", parentId: "fr-08" },
      { id: "fr-10", speaker: "B", text: "육아휴직 제도나 유연근무제 같은 정책이 필요한 이유가 그거야.", parentId: "fr-09" },
      { id: "fr-11", speaker: "A", text: "어르신들은 '그게 당연한 거 아니냐'고 하시던데, 세대 차이도 있어." },
      { id: "fr-12", speaker: "B", text: "세대 인식이 다른 건 사실이야. 근데 그걸 이유로 불평등을 유지하는 건 별개 문제야.", parentId: "fr-11" },
      { id: "fr-13", speaker: "A", text: "맞아. '원래 그래왔다'는 게 '옳다'는 의미는 아니니까.", parentId: "fr-12" },
      { id: "fr-14", speaker: "B", text: "그리고 아이들도 역할 분담을 배워야 한다고 봐. 어릴 때 집안일을 돕는 경험이 중요해.", parentId: "fr-13" },
      { id: "fr-15", speaker: "A", text: "아이들 가사 참여에 대해서는 어떤 기준이 좋을까?", parentId: "fr-14" },
      { id: "fr-16", speaker: "B", text: "나이에 맞는 수준에서, 성별 구분 없이 하는 게 핵심이라고 생각해.", parentId: "fr-15" },
      { id: "fr-17", speaker: "A", text: "아들한테 설거지, 딸한테 청소 이런 식으로 나누면 안 된다는 거지.", parentId: "fr-16" },
      { id: "fr-18", speaker: "B", text: "맞아. 어릴 때부터 그런 구분을 없애야 성인이 돼서도 자연스러워지지.", parentId: "fr-17" },
      { id: "fr-19", speaker: "A", text: "결국 가정 내 역할 분담이 사회 전체의 성평등과 연결된다는 거네.", parentId: "fr-18" },
      { id: "fr-20", speaker: "B", text: "그리고 그게 행복한 가정의 기본 조건이기도 하고. 누군가 지쳐 있으면 가족 전체에 영향을 미치니까.", parentId: "fr-19" },
      { id: "fr-21", speaker: "A", text: "오늘 대화하면서 '역할 분담'이 단순한 가사 문제가 아니라는 걸 새롭게 느꼈어.", parentId: "fr-20" },
      { id: "fr-22", speaker: "B", text: "나도. 처음엔 반반이냐 아니냐의 문제인 줄 알았는데 훨씬 넓은 맥락이 있었네.", parentId: "fr-21" },
    ],
  },
  {
    id: "low-quality",
    title: "환경 보호와 개인의 역할 (낮은 품질)",
    description: "상호참조가 적고 단절된 대화의 예시입니다. 루브릭 분석 비교용.",
    topic: "환경 보호, 개인 실천, 사회적 책임",
    chatHistory: [
      { id: "lq-01", speaker: "A", text: "환경 보호가 중요한 것 같아." },
      { id: "lq-02", speaker: "B", text: "응.", parentId: "lq-01" },
      { id: "lq-03", speaker: "A", text: "나는 분리수거 열심히 해." },
      { id: "lq-04", speaker: "B", text: "오늘 점심 뭐 먹었어?" },
      { id: "lq-05", speaker: "A", text: "김밥.", parentId: "lq-04" },
      { id: "lq-06", speaker: "B", text: "지구 온난화가 진짜 심각하대." },
      { id: "lq-07", speaker: "A", text: "맞아.", parentId: "lq-06" },
      { id: "lq-08", speaker: "B", text: "탄소 배출 줄여야 한다고 생각해." },
      { id: "lq-09", speaker: "A", text: "응 그렇지.", parentId: "lq-08" },
      { id: "lq-10", speaker: "B", text: "근데 나는 걸어 다니기 귀찮아." },
      { id: "lq-11", speaker: "A", text: "나도.", parentId: "lq-10" },
      { id: "lq-12", speaker: "B", text: "내일 체육 시간에 뭐 해?" },
      { id: "lq-13", speaker: "A", text: "축구인가?" },
      { id: "lq-14", speaker: "B", text: "재활용도 중요하지." },
      { id: "lq-15", speaker: "A", text: "맞아.", parentId: "lq-14" },
      { id: "lq-16", speaker: "B", text: "그냥 정부가 다 알아서 해야 하는 거 아닌가." },
      { id: "lq-17", speaker: "A", text: "응 맞아.", parentId: "lq-16" },
      { id: "lq-18", speaker: "B", text: "우리가 뭘 할 수 있겠어." },
      { id: "lq-19", speaker: "A", text: "그러게.", parentId: "lq-18" },
      { id: "lq-20", speaker: "B", text: "수업 끝나고 편의점 갈래?" },
    ],
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
